# Generated by Django 3.2.18 on 2023-03-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='EMAIL',
        ),
    ]
