# Generated by Django 3.2.18 on 2023-03-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_email_newsletter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='EMAIL',
            new_name='email',
        ),
    ]
